### PR TITLE
Refactor: rider links in sidebar

### PR DESCRIPTION
**Pull request by teesloane**
Commits are atomic. The goal here is show rider-specific links to dispatcher who are also riders. Along the way I did a bit of refactoring.

I still need to make it so that the toggleable "rider links" sticks open/close between pages, which might have to be done with javascript unless you have any ideas on how to do that application wide on the elixir side @mveytsman .

Screenshot:

CleanShot 2024-01-08 at 18 22 50@2x

### CODE REVIEW

**Comment by teesloane** [comment]
Update: removed toggling. Keep it simple.

CleanShot 2024-01-15 at 15 10 02@2x

**Review by mveytsman — APPROVED** [review]
Looks great 🚀

**Comment by mveytsman** [comment]
Is the fialing test just flakey?

**Comment by teesloane** [comment]
> Is the fialing test just flakey?

yes it's a bit flakey ❄️ .

**Pull request merged**
