### PR TITLE
Clearer login error

### PR DESCRIPTION
**Pull request by mveytsman**
This is part of #133 that's not covered by #148 
Screen Shot 2022-07-13 at 10 42 27 AM

### CODE REVIEW

**Comment by chadmohr** [comment]
Got it, show_field: false. Maybe I was being lazy :)

**Comment by mveytsman** [comment]
@chadmohr haha - I added the `:show_field` option in this PR just to be able to do this, it wasn't there before 😂 

For posterity can you review this one and/or request any changes on copy?

**Review by chadmohr — COMMENTED** [review]
'Need an account' should be changed to 'Sign up now'

**Comment by mveytsman** [comment]
> 'Need an account' should be changed to 'Sign up now'

I think that's out of scope in this PR and can just be done in yours. I just wanted to fix the error bit in this one...

**Comment by chadmohr** [comment]
Agreed

**Pull request merged**
