### PR TITLE
363 find a way to add images to delivery sign up

### LINKED ISSUE #363: Find a way to add images to delivery sign up
We got feedback from a rider:

> ... I'm missing the pictures that show the size and dimensions of the pick up. For example, for Fort York foodbank, it's really hard to picture what 1 food hamper looks like. Any chance you could put in photos again? It would help to know if I can manage the pick up.

### PR DESCRIPTION
**Pull request by mveytsman**
## Describe your changes

Closes #363 

Add images to programs

CleanShot 2024-06-25 at 17 00 46@2x

CleanShot 2024-06-25 at 17 05 18@2x

Update for dispatchers: 
> Hey folks, as requested you can now add photos to programs so we can show riders what the deliveries look like. I've gone ahead and updated the photos from the spreadsheet for <LIST HERE>

TODO:
~~- [ ] I think a generic description or notes would be good here. I think we have something in the db we should just expose it~~ #392 
- [x] Bug where when I delete a photo and upload a new one the deleted photo sticks around
- [x] Tests

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [x] If it is a core feature, I have added tests.
- [x] Are there other PRs or Issues that I should link to here?
- [x] Will this be part of a product update? If yes, please write one phrase
      about this update in the description above.

### CODE REVIEW

**Comment by teesloane** [comment]
Looking good so far! Maybe let's add a small header above the photos on the campaign signup to say "Photos campaign delivery" or something better than that.

**Comment by teesloane** [comment]
> Good idea!
> 
> CleanShot 2024-06-26 at 14 07 51@2x

I think I'd change "Campaign photos" to something a bit more descriptive:

<h3> Delivery examples</h3>
<div>{Program name} usually delivers {Enum.join(program.items)}</div>

---

Other than that, tested and good to go.

**Review by teesloane — APPROVED** [review]

**Comment by mveytsman** [comment]
I don't think they're always delivery examples though, eg sometimes they me be maps

May I'll leave it as photos of the delivery but not do the "usually delives" bit?

Also see #392

**Comment by mveytsman** [comment]
I realized #392 was already done, but I added a little photo description field to follow the spreadsheet example:

CleanShot 2024-06-27 at 17 55 13@2x

**Pull request merged**
