### PR TITLE
Added dates but they do not have functionality yet

### PR DESCRIPTION
**Pull request by dkagotho**
I added dates but they do not have functionality yet.

Screen Shot 2022-01-05 at 6 55 52 PM

### CODE REVIEW

**Comment by dkagotho** [comment]
Screen Shot 2022-01-11 at 10 46 47 AM

**Review by mveytsman — COMMENTED** [review]
This looks great! One small fix can you make sure the dot indicating it's today is centered in the desktop and mobile view?
Screen Shot 2022-01-11 at 12 11 13 PM
Screen Shot 2022-01-11 at 12 11 07 PM

**Comment by dkagotho** [comment]
Sure!

**Comment by dkagotho** [comment]
Is this better?
Screen Shot 2022-01-11 at 12 21 26 PM
Screen Shot 2022-01-11 at 12 21 40 PM

**Comment by dkagotho** [comment]
Screen Shot 2022-01-11 at 12 43 50 PM
Screen Shot 2022-01-11 at 12 43 42 PM

**Review by mveytsman — APPROVED** [review]

**Pull request merged**
